# Generated by Django 3.2.5 on 2021-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='personID',
            field=models.IntegerField(),
        ),
    ]
