# Generated by Django 3.2.5 on 2021-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0002_alter_income_personid'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='Date',
            field=models.TimeField(null=True),
        ),
    ]
