# Generated by Django 3.2.5 on 2021-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0004_remove_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
